; Technology File CIC 0.18um 1.8V/3.3V 1P6M Virtual Mixed Mode/RFCMOS Process 
; Version : 1.0
; Date Code : 05/15/2005


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName		Purpose#	Abbreviation	)
 ;( -----------		--------	------------	)
 ;User-Defined Purposes:
  ( power		1		pwd		)
  ( GSLAYER		2		gsl		)
  ( MCAP		3		mca		)
  ( BAR			4		bar		)
  ( ROUT		5		rot		)
  ( MRSYMBOL		11		syr		)
  ( CSYMBOL		12		syc		)
  ( BJTSYMBOL		13		syj		)
  ( DSYMBOL		14		syd		)
  ( LSYMBOL		15		syl		)
  ( MMSYMBOL		16		sym		)
  ( RFSYMBOL		17		syf		)
  ( DIOBLK		18		dbk		)
  ( IND			19		ind		)
  ( RFMOS_S		20		rfs		)
  ( SIZE1		21		sz1		)
  ( SIZE2		22		sz2		)
  ( SIZE3		23		sz3		)
  ( SIZE4		24		sz4		)
  ( SIZE5		25		sz5		)
  ( SIZE6		26		sz6		)
  ( SIZE7		27		sz7		)
  ( SIZE8		28		sz8		)
  ( SIZE9		29		sz9		)
  ( SIZE10		30		sza		)
  ( SIZE11		31		szb		)
  ( SIZE12		32		szc		)
  ( M1SLMK		33		sm1		)
  ( M2SLMK		34		sm2		)
  ( M3SLMK		35		sm3		)
  ( M4SLMK		36		sm4		)
  ( M5SLMK		37		sm5		)
  ( M6SLMK		38		sm6		)
  ( M7SLMK		39		sm7		)
  ( DIFFDMBK		49		dbd		)
  ( PO1DMBK		50		dbp		)
  ( M1DMBK		51		db1		)
  ( M2DMBK		52		db2		)
  ( M3DMBK		53		db3		)
  ( M4DMBK		54		db4		)
  ( M5DMBK		55		db5		)
  ( M6DMBK		56		db6		)
  ( M7DMBK		57		db7		)
  ( M8DMBK		58		db8		)
  ( M9DMBK		59		db9		)
  ( DTDMBK		60		dbt		)
  ( INDDMBK		61		dbi		)
  ( DIFFSLBK		62		sbd		)
  ( PO1SLBK		63		sbp		)
  ( M1SLBK		64		sb1		)
  ( M2SLBK		65		sb2		)
  ( M3SLBK		66		sb3		)
  ( M4SLBK		67		sb4		)
  ( M5SLBK		68		sb5		)
  ( M6SLBK		69		sb6		)
  ( M7SLBK		70		sb7		)
  ( M8SLBK		71		sb8		)
  ( M9SLBK		72		sb9		)
  ( INDSLBK		73		sbi		)
  ( DIFFDUMY		74		dmd		)
  ( PO1DUMY		75		dmp		)
  ( M1DUMY		76		dm1		)
  ( M2DUMY		77		dm2		)
  ( M3DUMY		78		dm3		)
  ( M4DUMY		79		dm4		)
  ( M5DUMY		80		dm5		)
  ( M6DUMY		81		dm6		)
  ( M7DUMY		82		dm7		)
  ( M8DUMY		83		dm8		)
  ( M9DUMY		84		dm9		)
  ( INDDUMY		85		dmi		)
  ( DIFFSLOT		86		dld		)
  ( PO1SLOT		87		slp		)
  ( M1SLOT		88		sl1		)
  ( M2SLOT		89		sl2		)
  ( M3SLOT		90		sl3		)
  ( M4SLOT		91		sl4		)
  ( M5SLOT		92		sl5		)
  ( M6SLOT		93		sl6		)
  ( M7SLOT		94		sl7		)
  ( M8SLOT		95		sl8		)
  ( M9SLOT		96		sl9		)
  ( INDSLOT		97		sli		)
  ( L2SLOT		98		sll		)
 
 ;System-Reserved Purposes:
  ( warning		234		wng		)
  ( tool1		235		tl1		)
  ( tool0		236		tl0		)
  ( label		237		lbl		)
  ( flight		238		flt		)
  ( error		239		err		)
  ( annotate		240		ant		)
  ( drawing1		241		dr1		)
  ( drawing2		242		dr2		)
  ( drawing3		243		dr3		)
  ( drawing4		244		dr4		)
  ( drawing5		245		dr5		)
  ( drawing6		246		dr6		)
  ( drawing7		247		dr7		)
  ( drawing8		248		dr8		)
  ( drawing9		249		dr9		)
  ( boundary		250		bnd		)
  ( pin			251		pin		)
  ( drawing 		252		drw		)
  ( net			253		net		)
  ( cell		254		cel		)
  ( all			255		all		)
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( SUBSTRATE			1	SUBSTRATE	)
  ( DIFF			2	DIFF		)
  ( PWEL			3	PWEL		)
  ( NW				4	NW		)
  ( DNW				7	DNW		)
  ( BPW				6	BPW		)
  ( TWEL			5	TWEL		)
  ( PWBLK			8	PWBLK		)
  ( PIMP			12	PIMP		)
  ( NIMP			13	NIMP		)
  ( VTP				14	VTP		)
  ( VTN				15	VTN		)
  ( VTPH			16	VTPH		)
  ( VTNH			17	VTNH		)
  ( PMINUS			18	PMINUS		)
  ( NMINUS			19	NMINUS		)
  ( LVT				20	LVT		)
  ( VTPL			21	VTPL		)
  ( VTPHL			22	VTPHL		)
  ( VTNL			23	VTNL		)
  ( VTNI			24	VTNI		)
  ( VTNHL			25	VTNHL		)
  ( VTNHI			26	VTNHI		)
  ( RESISTOR			28	RESISTOR	)
  ( VTNHH			29	VTNHH		)
  ( NPOLY			30	NPOLY		)
  ( ESD				32	ESD		)
  ( PESD			33	PESD		)
  ( CELLEX			34	CELLEX		)
  ( DT				35	DT		)
  ( MG				36	MG		)
  ( SAB				37	SAB		)
  ( OD2				38	OD2		)
  ( HRP				39	HRP		)
  ( CONT			40	CONT		)
  ( NWR				41	NWR		)
  ( PO1				42	PO1		)
  ( LIL				43	LIL		)
  ( VARACT			44	VARACT		)
  ( PPO_R_BLK			45	PPO_R_BLK	)
  ( ME1				47	ME1		)
  ( VIA1			48	VIA1		)
  ( ME2				49	ME2		)
  ( VIA2			50	VIA2		)
  ( ME3				51	ME3		)
  ( VIA3			52	VIA3		)
  ( ME4				53	ME4		)
  ( VIA4			54	VIA4		)
  ( ME5				55	ME5		)
  ( VIA5			56	VIA5		)
  ( ME6				57	ME6		)
  ( CTM				66	CTM		)
  ( PAD				67	PAD		)
  ( VI6				58	VI6		)
  ( ME7				59	ME7		)
  ( VI7				60	VI7		)
  ( ME8				61	ME8		)
  ( VI8				62	VI8		)
  ( ME9				63	ME9		)
  ( MMCH			64	MMCH		)
  ( MMCBP			65	MMCBP		)
  ( MFG67			68	MFG67		)
  ( L3				69	L3		)
  ( L4				70	L4		)
  ( MFG70			71	MFG70		)
  ( MFG71			72	MFG71		)
  ( MFG72			73	MFG72		)
  ( MFG73			74	MFG73		)
  ( MFG74			75	MFG74		)
  ( MFG75			76	MFG75		)
  ( MFG76			77	MFG76		)
  ( MFG77			78	MFG77		)
  ( MFG78			79	MFG78		)
  ( MFG79			80	MFG79		)
  ( MFG80			81	MFG80		)
  ( RSYMBOL			82	RSYMBOL		)
  ( PSYMBOL			83	PSYMBOL		)
  ( WSYMBOL			84	WSYMBOL		)
  ( TEXT			86	TEXT		)
  ( MSL				87	MSL		)
  ( IOMARK			88	IOMARK		)
  ( FUSEMARK			89	FUSEMARK	)
  ( FLPMARK			90	FLPMARK		)
  ( PADMARK			91	PADMARK		)
  ( IOID			92	IOID		)
  ( ROMID			94	ROMID		)
  ( DPID			95	DPID		)
  ( BLSPID			96	BLSPID		)
  ( XDIODE			97	XDIODE		)
  ( IRAM			98	IRAM		)
  ( BDSPID			99	BDSPID		)
  ( PO_TEXT			100	PO_TEXT		)
  ( M1_TEXT			101	M1_TEXT		)
  ( M2_TEXT			102	M2_TEXT		)
  ( M3_TEXT			103	M3_TEXT		)
  ( M4_TEXT			104	M4_TEXT		)
  ( M5_TEXT			105	M5_TEXT		)
  ( M6_TEXT			106	M6_TEXT		)
  ( MRSDUMMY			111	MRSDUMMY		)
  ( MIMDUMMY			112	MIMDUMMY		)
  ( BJTDUMMY			113	BJTDUMMY		)
  ( DioDUMMY			114	DioDUMMY		)
  ( CAD115			115	CAD115		)
  ( CAD116			116	CAD116		)
  ( INDDUMMY			117	INDDUMMY		)
  ( MMDUMMY			118	MMDUMMY		)
  ( RFDUMMY			119	RFDUMMY		)
  ( ACL				120	ACL		)
  ( PHL				121	PHL		)


 ;SyDIODE	stem-ReservedLayers:
  ( Unrouted		200	Unroute	)
  ( Row			201	Row	)
  ( Group		202	Group	)
  ( Cannotoccupy	203	noOcupy	)
  ( Canplace		204	Canplac	)
  ( hardFence		205	hardFnc	)
  ( softFence		206	softFnc	)
  ( y0			207	y0	)
  ( y1			208	y1	)
  ( y2			209	y2	)
  ( y3			210	y3	)
  ( y4			211	y4	)
  ( y5			212	y5	)
  ( y6			213	y6	)
  ( y7			214	y7	)
  ( y8			215	y8	)
  ( y9			216	y9	)
  ( designFlow		217	dsnFlow	)
  ( stretch		218	stretch	)
  ( edgeLayer		219	edgeLyr	)
  ( changedLayer	220	chngLyr	)
  ( unset		221	unset	)
  ( unknown		222	unknown	)
  ( spike		223	spike	)
  ( hiz			224	hiz	)
  ( resist		225	resist	)
  ( drive		226	drive	)
  ( supply		227	supply	)
  ( wire		228	wire	)
  ( pin			229	pin	)
  ( text		230	text	)
  ( device		231	device	)
  ( border		232	border	)
  ( snap		233	snap	)
  ( align		234	align	)
  ( prBoundary		235	prBndry	)
  ( instance		236	instnce	)
  ( annotate		237	anotate	)
  ( marker		238	marker	)
  ( select		239	select	)
  ( grid		251	grid	)
  ( axis		252	axis	)
  ( hilite		253	hilite	)
  ( background		254	bkground)
 ) ;techLayers   

 techLayerPurposePriorities(    
 ;layers are ordered from lowest to highest priority
 ;( LayerName			Purpose		)
 ;( ---------			-------		)
  ( background			drawing		)
  ( grid			drawing		)
  ( grid			drawing1	)
  ( annotate			drawing		)
  ( annotate			drawing1	)
  ( annotate			drawing2	)
  ( annotate			drawing3	)
  ( annotate			drawing4	)
  ( annotate			drawing5	)
  ( annotate			drawing6	)
  ( annotate			drawing7	)
  ( annotate			drawing8	)
  ( annotate			drawing9	)
  ( instance			drawing		)
  ( instance			label		)
  ( prBoundary			drawing		)
  ( prBoundary			boundary	)
  ( prBoundary			label		)
  ( align			drawing		)
  ( hardFence			drawing		)
  ( softFence			drawing		)
  ( text			drawing		)
  ( text			drawing1	)
  ( text			drawing2	)
  ( border			drawing		)
  ( device			drawing		)
  ( device			label		)
  ( device			drawing1	)
  ( device			drawing2	)
  ( device			annotate	)
  ( wire			drawing		)
  ( wire			label		)
  ( wire			flight		)
  ( pin				label		)
  ( pin				drawing		)
  ( pin				annotate	)
  ( axis			drawing		)
  ( edgeLayer			drawing		)
  ( edgeLayer			pin		)
  ( snap			drawing		)
  ( stretch			drawing		)
  ( y0				drawing		)
  ( y1				drawing		)
  ( y2				drawing		)
  ( y3				drawing		)
  ( y4				drawing		)
  ( y5				drawing		)
  ( y6				drawing		)
  ( y7				drawing		)
  ( y8				drawing		)
  ( y9				drawing		)
  ( hilite			drawing		)
  ( hilite			drawing1	)
  ( hilite			drawing2	)
  ( hilite			drawing3	)
  ( hilite			drawing4	)
  ( hilite			drawing5	)
  ( hilite			drawing6	)
  ( hilite			drawing7	)
  ( hilite			drawing8	)
  ( hilite			drawing9	)
  ( select			drawing		)
  ( drive			drawing		)
  ( hiz				drawing		)
  ( resist			drawing		)
  ( spike			drawing		)
  ( supply			drawing		)
  ( unknown			drawing		)
  ( unset			drawing		)
  ( designFlow			drawing		)
  ( designFlow			drawing1	)
  ( designFlow			drawing2	)
  ( designFlow			drawing3	)
  ( designFlow			drawing4	)
  ( designFlow			drawing5	)
  ( designFlow			drawing6	)
  ( designFlow			drawing7	)
  ( designFlow			drawing8	)
  ( designFlow			drawing9	)
  ( changedLayer		tool0		)
  ( changedLayer		tool1		)
  ( marker			warning		)
  ( marker			error		)
  ( Row				drawing		)
  ( Row				label		)
  ( Group			drawing		)
  ( Group			label		)
  ( Cannotoccupy		drawing		)
  ( Cannotoccupy		boundary	)
  ( Canplace			drawing		)
  ( Unrouted			drawing		)
  ( Unrouted			drawing1	)
  ( Unrouted			drawing2	)
  ( Unrouted			drawing3	)
  ( Unrouted			drawing4	)
  ( Unrouted			drawing5	)
  ( Unrouted			drawing6	)
  ( Unrouted			drawing7	)
  ( Unrouted			drawing8	)
  ( Unrouted			drawing9	)
  ( SUBSTRATE			drawing		)
  ( DIFF			drawing		)
  ( PWEL			drawing		)
  ( NW				drawing		)
  ( DNW				drawing		)
  ( BPW				drawing		)
  ( TWEL			drawing		)
  ( PWBLK			drawing		)
  ( PIMP			drawing		)
  ( NIMP			drawing		)
  ( VTP				drawing		)
  ( VTN				drawing		)
  ( VTPH			drawing		)
  ( VTNH			drawing		)
  ( PMINUS			drawing		)
  ( NMINUS			drawing		)
  ( LVT				drawing		)
  ( VTPL			drawing		)
  ( VTPHL			drawing		)
  ( VTNL			drawing		)
  ( VTNI			drawing		)
  ( VTNHL			drawing		)
  ( VTNHI			drawing		)
  ( RESISTOR			drawing		)
  ( VTNHH			drawing		)
  ( NPOLY			drawing		)
  ( ESD				drawing		)
  ( PESD			drawing		)
  ( CELLEX			drawing		)
  ( DT				drawing		)
  ( MG				drawing		)
  ( SAB				drawing		)
  ( OD2				drawing		)
  ( HRP				drawing		)
  ( CONT			drawing		)
  ( NWR				drawing		)
  ( PO1				drawing		)
  ( LIL				drawing		)
  ( VARACT			drawing		)
  ( PPO_R_BLK			drawing		)
  ( ME1				drawing		)
  ( VIA1			drawing		)
  ( ME2				drawing		)
  ( VIA2			drawing		)
  ( ME3				drawing		)
  ( VIA3			drawing		)
  ( ME4				drawing		)
  ( VIA4			drawing		)
  ( ME5				drawing		)
  ( VIA5				drawing		)
  ( ME6				drawing		)
  ( VI6				drawing		)
  ( ME7				drawing		)
  ( VI7				drawing		)
  ( ME8				drawing		)
  ( VI8				drawing		)
  ( ME9				drawing		)
  ( MMCH			drawing		)
  ( MMCH			GSLAYER		)
  ( MMCBP			drawing		)
  ( CTM				drawing		)
  ( PAD				drawing		)
  ( MFG67			drawing		)
  ( L3				drawing		)
  ( L4				drawing		)
  ( MFG70			DIFFDMBK	)
  ( MFG71			PO1DMBK		)
  ( MFG72			M1DMBK		)
  ( MFG73			M2DMBK		)
  ( MFG74			M3DMBK		)
  ( MFG75			M4DMBK		)
  ( MFG76			M5DMBK		)
  ( MFG77			M6DMBK		)
  ( MFG78			M7DMBK		)
  ( MFG79			M8DMBK		)
  ( MFG80			M9DMBK		)
  ( DT				DTDMBK		)
  ( MFG80			INDDMBK		)
  ( MFG72			M1SLBK		)
  ( MFG73			M2SLBK		)
  ( MFG74			M3SLBK		)
  ( MFG75			M4SLBK		)
  ( MFG76			M5SLBK		)
  ( MFG77			M6SLBK		)
  ( MFG78			M7SLBK		)
  ( MFG79			M8SLBK		)
  ( MFG80			M9SLBK		)
  ( MFG80			INDSLBK		)
  ( MFG72			M1SLMK		)
  ( MFG73			M2SLMK		)
  ( MFG74			M3SLMK		)
  ( MFG75			M4SLMK		)
  ( MFG76			M5SLMK		)
  ( MFG77			M6SLMK		)
  ( MFG78			M7SLMK		)
  ( MFG70			DIFFDUMY	)
  ( MFG71			PO1DUMY		)
  ( MFG72			M1DUMY		)
  ( MFG73			M2DUMY		)
  ( MFG74			M3DUMY		)
  ( MFG75			M4DUMY		)
  ( MFG76			M5DUMY		)
  ( MFG77			M6DUMY		)
  ( MFG78			M7DUMY		)
  ( MFG79			M8DUMY		)
  ( MFG80			M9DUMY		)
  ( MFG80			INDDUMY		)
  ( MFG72			M1SLOT		)
  ( MFG73			M2SLOT		)
  ( MFG74			M3SLOT		)
  ( MFG75			M4SLOT		)
  ( MFG76			M5SLOT		)
  ( MFG77			M6SLOT		)
  ( MFG78			M7SLOT		)
  ( MFG79			M8SLOT		)
  ( MFG80			M9SLOT		)
  ( MFG67			L2SLOT		)
  ( MFG80			INDSLOT		)
  ( RSYMBOL			drawing		)
  ( PSYMBOL			drawing		)
  ( WSYMBOL			drawing		)
  ( TEXT			drawing		)
  ( MSL				drawing		)
  ( IOMARK			drawing		)
  ( FUSEMARK			drawing		)
  ( FLPMARK			drawing		)
  ( PADMARK			drawing		)
  ( IOID			drawing		)
  ( ROMID			drawing		)
  ( DPID			drawing		)
  ( BLSPID			drawing		)
  ( XDIODE			drawing		)
  ( IRAM			drawing		)
  ( BDSPID			drawing		)
  ( PO_TEXT			drawing		)
  ( M1_TEXT			drawing		)
  ( M2_TEXT			drawing		)
  ( M3_TEXT			drawing		)
  ( M4_TEXT			drawing		)
  ( M5_TEXT			drawing		)
  ( M6_TEXT			drawing		)
  ( MRSDUMMY			MRSYMBOL	)
  ( MIMDUMMY			CSYMBOL		)
  ( MIMDUMMY			MCAP		)
  ( BJTDUMMY			BJTSYMBOL	)
  ( DioDUMMY			DSYMBOL		)
  ( CAD115			DIOBLK		)
  ( INDDUMMY			LSYMBOL		)
  ( INDDUMMY			IND		)
  ( MMDUMMY			MMSYMBOL	)
  ( RFDUMMY			RFSYMBOL	)
  ( RFDUMMY			RFMOS_S		)
  ( MRSDUMMY			SIZE1		)
  ( MIMDUMMY			SIZE2		)
  ( BJTDUMMY			SIZE3		)
  ( DioDUMMY			SIZE4		)
  ( CAD115			SIZE5		)
  ( CAD116			SIZE6		)
  ( INDDUMMY			SIZE7		)
  ( MMDUMMY			SIZE8		)
  ( RFDUMMY			SIZE9		)
  ( MRSDUMMY			SIZE10		)
  ( MIMDUMMY			SIZE11		)
  ( BJTDUMMY			SIZE12		)
  ( ACL				drawing		)
  ( PHL				drawing		)
 ) ;techLayerPurposePriorities



 techDisplays(
 ;( LayerName		Purpose		Packet		Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------		-------		------		--- --- --------- ------- ----- )
  ( background		drawing 	background	t nil t nil nil )
  ( grid		drawing		grid 		t nil t nil nil )
  ( grid		drawing1	grid1		t nil t nil nil )
  ( annotate		drawing		annotate	t t t t nil )
  ( annotate		drawing1	annotate1 	t t t t nil )
  ( annotate		drawing2	annotate2 	t t t t nil )
  ( annotate		drawing3	annotate3 	t t t t nil )
  ( annotate		drawing4	annotate4 	t t t t nil )
  ( annotate		drawing5	annotate5 	t t t t nil )
  ( annotate		drawing6	annotate6 	t t t t nil )
  ( annotate		drawing7	annotate7 	t t t t nil )
  ( annotate		drawing8	annotate8 	t t t t nil )
  ( annotate		drawing9	annotate9 	t t t t nil )
  ( instance		drawing 	instance	t t t t nil )
  ( instance		label 		instanceLbl 	t t t t nil )
  ( prBoundary		drawing 	prBoundary	t t t t nil )
  ( prBoundary		boundary	prBoundaryBnd	t t t t nil )
  ( prBoundary		label 		prBoundaryLbl	t t t t nil )
  ( align		drawing		defaultPacket	t t t t nil )
  ( hardFence		drawing		hardFence 	t t t t nil )
  ( softFence		drawing		softFence 	t t t t nil )
  ( text		drawing		text 		t t t t nil )
  ( text		drawing1	text1		t t t t nil )
  ( text		drawing2	text2		t t t t nil )
  ( border		drawing 	border 		t t t t nil )
  ( device		drawing 	device 		t t t t nil )
  ( device		label 		deviceLbl 	t t t t nil )
  ( device		drawing1	device1		t t t t nil )
  ( device		drawing2	device2		t t t t nil )
  ( device		annotate	deviceAnt 	t t t t nil )
  ( wire		drawing		wire 		t t t t nil )
  ( wire		label 		wireLbl		t t t t nil )
  ( wire		flight		wireFlt		t t t t nil )
  ( pin			label 		pinLbl 		t t t t nil )
  ( pin			drawing 	pin		t t t t nil )
  ( pin			annotate	pinAnt 		t t t t nil )
  ( axis		drawing 	axis 		t nil t t nil )
  ( edgeLayer		drawing 	edgeLayer 	t t t t nil )
  ( edgeLayer		pin		edgeLayerPin	t t t t nil )
  ( snap		drawing 	snap 		t t t t nil )
  ( stretch 		drawing 	stretch		t t t t nil )
  ( y0 			drawing		y0		t t t t nil )
  ( y1 			drawing		y1		t t t t nil )
  ( y2 			drawing		y2		t t t t nil )
  ( y3 			drawing		y3		t t t t nil )
  ( y4 			drawing		y4		t t t t nil )
  ( y5 			drawing		y5		t t t t nil )
  ( y6 			drawing		y6		t t t t nil )
  ( y7 			drawing		y7		t t t t nil )
  ( y8 			drawing		y8		t t t t nil )
  ( y9 			drawing		y9		t t t t nil )
  ( hilite		drawing		hilite 		t t t t nil )
  ( hilite		drawing1	hilite1		t t t t nil )
  ( hilite		drawing2	hilite2		t t t t nil )
  ( hilite		drawing3	hilite3		t t t t nil )
  ( hilite		drawing4	hilite4		t t t t nil )
  ( hilite		drawing5	hilite5		t t t t nil )
  ( hilite		drawing6	hilite6		t t t t nil )
  ( hilite		drawing7	hilite7		t t t t nil )
  ( hilite		drawing8	hilite8		t t t t nil )
  ( hilite		drawing9	hilite9		t t t t nil )
  ( select		drawing 	select 		t t t t nil )
  ( drive 		drawing 	drive		t t t t nil )
  ( hiz			drawing 	hiz		t t t t nil )
  ( resist		drawing 	resist 		t t t t nil )
  ( spike 		drawing 	spike		t t t t nil )
  ( supply		drawing 	supply 		t t t t nil )
  ( unknown 		drawing 	unknown		t t t t nil )
  ( unset 		drawing 	unset		t t t t nil )
  ( designFlow 		drawing 	designFlow	t t t nil nil )
  ( designFlow 		drawing1	designFlow1 	t t t nil nil )
  ( designFlow 		drawing2	designFlow2 	t t t nil nil )
  ( designFlow 		drawing3	designFlow3 	t t t nil nil )
  ( designFlow 		drawing4	designFlow4 	t t t nil nil )
  ( designFlow 		drawing5	designFlow5 	t t t nil nil )
  ( designFlow 		drawing6	designFlow6 	t t t nil nil )
  ( designFlow 		drawing7	designFlow7 	t t t nil nil )
  ( designFlow 		drawing8	designFlow8 	t t t nil nil )
  ( designFlow 		drawing9	designFlow9 	t t t nil nil )
  ( changedLayer	tool0 		changedLayerTl0	nil nil t nil nil )
  ( changedLayer	tool1 		changedLayerTl1	nil nil t nil nil )
  ( marker		warning 	markerWarn	t t t t nil )
  ( marker		error 		markerErr 	t t t t nil )
  ( Row			drawing 	Row		t t t t nil )
  ( Row			label 		RowLbl 		t t t t nil )
  ( Group 		drawing 	Group		t t t t nil )
  ( Group		label 		GroupLbl	t t t t nil )
  ( Cannotoccupy	drawing 	Cannotoccupy	t t t t nil )
  ( Cannotoccupy 	boundary	CannotoccupyBnd	t t t t nil )
  ( Canplace		drawing 	Canplace	t t t t nil )
  ( Unrouted		drawing 	Unrouted	t t t t nil )
  ( Unrouted		drawing1	Unrouted1 	t t t t nil )
  ( Unrouted		drawing2	Unrouted2 	t t t t nil )
  ( Unrouted		drawing3	Unrouted3 	t t t t nil )
  ( Unrouted		drawing4	Unrouted4 	t t t t nil )
  ( Unrouted		drawing5	Unrouted5 	t t t t nil )
  ( Unrouted		drawing6	Unrouted6 	t t t t nil )
  ( Unrouted		drawing7	Unrouted7 	t t t t nil )
  ( Unrouted		drawing8	Unrouted8 	t t t t nil )
  ( Unrouted		drawing9	Unrouted9 	t t t t nil )
  ( SUBSTRATE		drawing		SUBSTRATE	t t t t nil ) 
  ( DIFF		drawing		DIFF	 	t t t t t ) 
  ( PWEL		drawing		PWEL	 	t t t t nil ) 
  ( NW			drawing		NW	 	t t t t t ) 
  ( DNW			drawing		DNW		t t t t t ) 
  ( BPW			drawing		BPW		t t t t nil ) 
  ( TWEL		drawing		TWEL	 	t t t t nil ) 
  ( PWBLK		drawing		PWBLK	 	t t t t t ) 
  ( PIMP		drawing		PIMP		t t t t t ) 
  ( NIMP		drawing		NIMP		t t t t t ) 
  ( VTP			drawing		VTP		t t t t nil ) 
  ( VTN			drawing		VTN		t t t t nil ) 
  ( VTPH		drawing		VTPH		t t t t nil ) 
  ( VTNH		drawing		VTNH		t t t t nil ) 
  ( PMINUS		drawing		PMINUS		t t t t nil ) 
  ( NMINUS		drawing		NMINUS		t t t t nil ) 
  ( LVT			drawing		LVT		t t t t nil ) 
  ( VTPL		drawing		VTPL		t t t t t ) 
  ( VTPHL		drawing		VTPHL		t t t t t ) 
  ( VTNL		drawing		VTNL		t t t t t ) 
  ( VTNI		drawing		VTNI		t t t t t ) 
  ( VTNHL		drawing		VTNHL		t t t t t ) 
  ( VTNHI		drawing		VTNHI 		t t t t nil )
  ( RESISTOR		drawing		RESISTOR 	t t t t nil )
  ( VTNHH		drawing		VTNHH		t t t t nil )
  ( NPOLY		drawing		NPOLY		t t t t nil )
  ( ESD			drawing		ESD		t t t t nil ) 
  ( PESD		drawing		PESD		t t t t nil ) 
  ( CELLEX 		drawing		CELLEX		t t t t nil )
  ( DT			drawing		DT		t t t t nil )
  ( MG			drawing		MG		t t t t nil )
  ( SAB			drawing		SAB		t t t t t ) 
  ( OD2			drawing		OD2		t t t t t ) 
  ( HRP			drawing		HRP		t t t t t ) 
  ( CONT		drawing		CONT	 	t t t t t ) 
  ( NWR			drawing		NWR		t t t t t ) 
  ( PO1			drawing		PO1		t t t t t ) 
  ( PO_TEXT		drawing		PO_TEXT		t t t t t ) 
  ( LIL			drawing		LIL 		t t t t nil )
  ( VARACT		drawing		VARACT		t t t t t ) 
  ( PPO_R_BLK 		drawing		PPO_R_BLK	t t t t nil )
  ( ME1			drawing		ME1		t t t t t ) 
  ( M1_TEXT		drawing		M1_TEXT		t t t t t ) 
  ( VIA1		drawing		VIA1		t t t t t ) 
  ( ME2			drawing		ME2		t t t t t ) 
  ( M2_TEXT		drawing		M2_TEXT		t t t t t ) 
  ( VIA2		drawing		VIA2		t t t t t ) 
  ( ME3			drawing		ME3		t t t t t ) 
  ( M3_TEXT		drawing		M3_TEXT		t t t t t ) 
  ( VIA3		drawing		VIA3		t t t t t ) 
  ( ME4			drawing		ME4		t t t t t ) 
  ( M4_TEXT		drawing		M4_TEXT		t t t t t ) 
  ( VIA4		drawing		VIA4		t t t t t ) 
  ( ME5			drawing		ME5		t t t t t ) 
  ( M5_TEXT		drawing		M5_TEXT		t t t t t ) 
  ( CTM			drawing		CTM		t t t t t ) 
  ( VIA5		drawing		VIA5		t t t t t ) 
  ( ME6			drawing		ME6		t t t t t ) 
  ( M6_TEXT		drawing		M6_TEXT		t t t t t ) 
  ( VI6			drawing		VI6		t t t t nil ) 
  ( ME7			drawing		ME7		t t t t nil ) 
  ( VI7			drawing		VI7		t t t t nil ) 
  ( ME8			drawing		ME8		t t t t nil ) 
  ( VI8			drawing		VI8		t t t t nil )
  ( ME9			drawing		ME9		t t t t nil )
  ( MMCH		GSLAYER		MMCH		t t t t nil )
  ( MMCH		drawing		MMCH		t t t t nil )
  ( MMCBP		drawing		MMCBP 		t t t t nil )
  ( PAD			drawing		PAD	 	t t t t t ) 
  ( MFG67		drawing		MFG67	 	t t t t nil ) 
  ( L3			drawing		L3	 	t t t t nil ) 
  ( L4 			drawing		L4	 	t t t t nil ) 
; dummy block begin
  ( MFG70		DIFFDMBK	DIFFDMBK	t t t t nil )
  ( MFG71		PO1DMBK		PO1DMBK		t t t t nil )
  ( MFG72		M1DMBK		M1DMBK		t t t t nil )
  ( MFG73		M2DMBK		M2DMBK		t t t t nil )
  ( MFG74		M3DMBK		M3DMBK		t t t t nil )
  ( MFG75		M4DMBK		M4DMBK		t t t t nil )
  ( MFG76		M5DMBK		M5DMBK		t t t t nil )
  ( MFG77		M6DMBK		M6DMBK		t t t t nil )
; dummy block END
  ( MFG78		M7DMBK		M7DMBK		t t t t nil )
  ( MFG79		M8DMBK		M8DMBK		t t t t nil )
  ( MFG80		M9DMBK		M9DMBK		t t t t nil )
  ( DT			DTDMBK		DTDMBK		t t t t nil )
  ( MFG80		INDDMBK		INDDMBK		t t t t nil )
  ( MFG72		M1SLBK		M1SLBK		t t t t nil )
  ( MFG73		M2SLBK		M2SLBK		t t t t nil )
  ( MFG74		M3SLBK		M3SLBK		t t t t nil )
  ( MFG75		M4SLBK		M4SLBK		t t t t nil )
  ( MFG76		M5SLBK		M5SLBK		t t t t nil )
  ( MFG77		M6SLBK		M6SLBK		t t t t nil )
  ( MFG78		M7SLBK		M7SLBK		t t t t nil )
  ( MFG79		M8SLBK		M8SLBK		t t t t nil )
  ( MFG80		M9SLBK		M9SLBK		t t t t nil )
  ( MFG80		INDSLBK		INDSLBK		t t t t nil )
  ( MFG72		M1SLMK		M1SLMK		t t t t nil )
  ( MFG73		M2SLMK		M2SLMK		t t t t nil )
  ( MFG74		M3SLMK		M3SLMK		t t t t nil )
  ( MFG75		M4SLMK		M4SLMK		t t t t nil )
  ( MFG76		M5SLMK		M5SLMK		t t t t nil )
  ( MFG77		M6SLMK		M6SLMK		t t t t nil )
  ( MFG78		M7SLMK		M7SLMK		t t t t nil )
  ( MFG70		DIFFDUMY	DIFFDUMY	t t t t nil )
  ( MFG71		PO1DUMY		PO1DUMY		t t t t nil )
  ( MFG72		M1DUMY		M1DUMY		t t t t nil )
  ( MFG73		M2DUMY		M2DUMY		t t t t nil )
  ( MFG74		M3DUMY		M3DUMY		t t t t nil )
  ( MFG75		M4DUMY		M4DUMY		t t t t nil )
  ( MFG76		M5DUMY		M5DUMY		t t t t nil )
  ( MFG77		M6DUMY		M6DUMY		t t t t nil )
  ( MFG78		M7DUMY		M7DUMY		t t t t nil )
  ( MFG79		M8DUMY		M8DUMY		t t t t nil )
  ( MFG80		M9DUMY		M9DUMY		t t t t nil )
  ( MFG80		INDDUMY		INDDUMY		t t t t nil )
  ( MFG72		M1SLOT		M1SLOT		t t t t nil )
  ( MFG73		M2SLOT		M2SLOT		t t t t nil )
  ( MFG74		M3SLOT		M3SLOT		t t t t nil )
  ( MFG75		M4SLOT		M4SLOT		t t t t nil )
  ( MFG76		M5SLOT		M5SLOT		t t t t nil )
  ( MFG77		M6SLOT		M6SLOT		t t t t nil )
  ( MFG78		M7SLOT		M7SLOT		t t t t nil )
  ( MFG79		M8SLOT		M8SLOT		t t t t nil )
  ( MFG80		M9SLOT		M9SLOT		t t t t nil )
  ( MFG67		L2SLOT		L2SLOT		t t t t nil )
  ( MFG80		INDSLOT		INDSLOT		t t t t nil )
  ( RSYMBOL		drawing		RSYMBOL		t t t t t ) 
  ( PSYMBOL		drawing		PSYMBOL		t t t t t ) 
  ( WSYMBOL		drawing		WSYMBOL		t t t t t ) 
  ( TEXT		drawing		TEXT		t t t t nil ) 
  ( MSL			drawing		MSL		t t t t nil ) 
  ( IOMARK		drawing		IOMARK	 	t t t t nil ) 
  ( FUSEMARK		drawing		FUSEMARK	t t t t nil )
  ( FLPMARK		drawing		FLPMARK		t t t t nil )
  ( PADMARK		drawing		PADMARK		t t t t nil )
  ( IOID		drawing		IOID		t t t t nil ) 
  ( ROMID		drawing		ROMID		t t t t nil ) 
  ( DPID		drawing		DPID		t t t t nil ) 
  ( BLSPID 		drawing		BLSPID		t t t t nil )
  ( XDIODE 		drawing		XDIODE		t t t t nil )
  ( IRAM		drawing		IRAM		t t t t nil ) 
  ( BDSPID 		drawing		BDSPID		t t t t nil )
  ( MRSDUMMY		MRSYMBOL	MRSYMBOL	t t t t t )
  ( MIMDUMMY		CSYMBOL		CSYMBOL		t t t t t )
  ( MIMDUMMY		MCAP		MCAP		t t t t nil )
  ( BJTDUMMY		BJTSYMBOL	BJTSYMBOL	t t t t t )
  ( DioDUMMY		DSYMBOL		DSYMBOL		t t t t t )
  ( CAD115		DIOBLK		DIOBLK		t t t t nil )
  ( INDDUMMY		LSYMBOL		LSYMBOL		t t t t t )
  ( INDDUMMY		IND		IND		t t t t t )
  ( MMDUMMY		MMSYMBOL	MMSYMBOL	t t t t nil )
  ( RFDUMMY		RFSYMBOL	RFSYMBOL	t t t t nil )
  ( RFDUMMY		RFMOS_S		RFMOS_S		t t t t nil )
  ( MRSDUMMY		SIZE1		SIZE1		t t t t nil )
  ( MIMDUMMY		SIZE2		SIZE2		t t t t nil )
  ( BJTDUMMY		SIZE3		SIZE3		t t t t nil )
  ( DioDUMMY		SIZE4		SIZE4		t t t t nil )
  ( CAD115		SIZE5		SIZE5		t t t t nil )
  ( CAD116		SIZE6		SIZE6		t t t t nil )
  ( INDDUMMY		SIZE7		SIZE7		t t t t nil )
  ( MMDUMMY		SIZE8		SIZE8		t t t t nil )
  ( RFDUMMY		SIZE9		SIZE9		t t t t nil )
  ( MRSDUMMY		SIZE10		SIZE10		t t t t nil )
  ( MIMDUMMY		SIZE11		SIZE11		t t t t nil )
  ( BJTDUMMY		SIZE12		SIZE12		t t t t nil )
  ( ACL			drawing		ACL		t t t t nil )
  ( PHL			drawing		PHL		t t t t nil )
) ;techDisplays

techLayerProperties(
;( PropName               Layer1 [ Layer2 ]            PropValue )
)

) ;layerDefinitions

layerRules(
 streamLayers(
;(layerstreamNumberdataTypetranslate)
;(----------------------------------)
  ( ("DIFF" "drawing")		1	0	t	)
  ( ("PWEL" "drawing")		2	0	t	)
  ( ("NW" "drawing")		3	0	t	)
  ( ("DNW" "drawing")		6	0	t	)
  ( ("BPW" "drawing")		5	0	t	)
  ( ("TWEL" "drawing")		4	0	t	)
  ( ("PWBLK" "drawing")		7	0	t	)
  ( ("PIMP" "drawing")		11	0	t	)
  ( ("NIMP" "drawing")		12	0	t	)
  ( ("VTP" "drawing")		13	0	t	)
  ( ("VTN" "drawing")		14	0	t	)
  ( ("VTPH" "drawing")		15	0	t	)
  ( ("VTNH" "drawing")		16	0	t	)
  ( ("PMINUS" "drawing")	17	0	t	)
  ( ("NMINUS" "drawing")	18	0	t	)
  ( ("LVT" "drawing")		19	0	t	)
  ( ("VTPL" "drawing")		20	0	t	)
  ( ("VTPHL" "drawing")		21	0	t	)
  ( ("VTNL" "drawing")		22	0	t	)
  ( ("VTNI" "drawing")		23	0	t	)
  ( ("VTNHL" "drawing")		24	0	t	)
  ( ("VTNHI" "drawing")		26	0	t	)
  ( ("RESISTOR" "drawing")	27	0	t	)
  ( ("VTNHH" "drawing")		28	0	t	)
  ( ("NPOLY" "drawing")		29	0	t	)
  ( ("ESD" "drawing")		31	0	t	)
  ( ("PESD" "drawing")		32	0	t	)
  ( ("CELLEX" "drawing")	33	0	t	)
  ( ("DT" "drawing")		34	0	t	)
  ( ("MG" "drawing")		35	0	t	)
  ( ("SAB" "drawing")		36	0	t	)
  ( ("OD2" "drawing")		37	0	t	)
  ( ("HRP" "drawing")		38	0	t	)
  ( ("CONT" "drawing")		39	0	t	)
  ( ("NWR" "drawing")		40	0	t	)
  ( ("PO1" "drawing")		41	0	t	)
  ( ("LIL" "drawing")		42	0	t	)
  ( ("VARACT" "drawing")	43	0	t	)
  ( ("PPO_R_BLK" "drawing")	44	0	t	)
  ( ("ME1" "drawing")		46	0	t	)
  ( ("VIA1" "drawing")		47	0	t	)
  ( ("ME2" "drawing")		48	0	t	)
  ( ("VIA2" "drawing")		49	0	t	)
  ( ("ME3" "drawing")		50	0	t	)
  ( ("VIA3" "drawing")		51	0	t	)
  ( ("ME4" "drawing")		52	0	t	)
  ( ("VIA4" "drawing")		53	0	t	)
  ( ("ME5" "drawing")		54	0	t	)
  ( ("VIA5" "drawing")		55	0	t	)
  ( ("ME6" "drawing")		56	0	t	)
  ( ("VI6" "drawing")		57	0	t	)
  ( ("ME7" "drawing")		58	0	t	)
  ( ("VI7" "drawing")		59	0	t	)
  ( ("ME8" "drawing")		60	0	t	)
  ( ("VI8" "drawing")		61	0	t	)
  ( ("ME9" "drawing")		62	0	t	)
  ( ("MMCH" "GSLAYER")		63	0	t	)
  ( ("MMCH" "drawing")		63	37	t	)
  ( ("MMCBP" "drawing")		64	0	t	)
  ( ("CTM" "drawing")		65	0	t	)
  ( ("PAD" "drawing")		66	0	t	)
  ( ("MFG67" "drawing")		67	0	t	)
  ( ("L3" "drawing")		68	0	t	)
  ( ("L4" "drawing")		69	0	t	)
  ( ("MFG70" "DIFFDMBK")	70	1	t	)
  ( ("MFG71" "PO1DMBK")		71	1	t	)
  ( ("MFG72" "M1DMBK")		72	1	t	)
  ( ("MFG73" "M2DMBK")		73	1	t	)
  ( ("MFG74" "M3DMBK")		74	1	t	)
  ( ("MFG75" "M4DMBK")		75	1	t	)
  ( ("MFG76" "M5DMBK")		76	1	t	)
  ( ("MFG77" "M6DMBK")		77	1	t	)
  ( ("MFG78" "M7DMBK")		78	1	t	)
  ( ("MFG79" "M8DMBK")		79	1	t	)
  ( ("MFG80" "M9DMBK")		80	1	t	)
  ( ("DT" "DTDMBK")		34	1	t	)
  ( ("MFG80" "INDDMBK")		80	100	t	)
  ( ("MFG72" "M1SLBK")		72	2	t	)
  ( ("MFG73" "M2SLBK")		73	2	t	)
  ( ("MFG74" "M3SLBK")		74	2	t	)
  ( ("MFG75" "M4SLBK")		75	2	t	)
  ( ("MFG76" "M5SLBK")		76	2	t	)
  ( ("MFG77" "M6SLBK")		77	2	t	)
  ( ("MFG78" "M7SLBK")		78	2	t	)
  ( ("MFG79" "M8SLBK")		79	2	t	)
  ( ("MFG80" "M9SLBK")		80	2	t	)
  ( ("MFG80" "INDSLBK")		80	101	t	)
  ( ("MFG72" "M1SLMK")		72	7	t	)
  ( ("MFG73" "M2SLMK")		73	7	t	)
  ( ("MFG74" "M3SLMK")		74	7	t	)
  ( ("MFG75" "M4SLMK")		75	7	t	)
  ( ("MFG76" "M5SLMK")		76	7	t	)
  ( ("MFG77" "M6SLMK")		77	7	t	)
  ( ("MFG78" "M7SLMK")		78	7	t	)
  ( ("MFG70" "DIFFDUMY")	70	8	t	)
  ( ("MFG71" "PO1DUMY")		71	8	t	)
  ( ("MFG72" "M1DUMY")		72	8	t	)
  ( ("MFG73" "M2DUMY")		73	8	t	)
  ( ("MFG74" "M3DUMY")		74	8	t	)
  ( ("MFG75" "M4DUMY")		75	8	t	)
  ( ("MFG76" "M5DUMY")		76	8	t	)
  ( ("MFG77" "M6DUMY")		77	8	t	)
  ( ("MFG78" "M7DUMY")		78	8	t	)
  ( ("MFG79" "M8DUMY")		79	8	t	)
  ( ("MFG80" "M9DUMY")		80	8	t	)
  ( ("MFG80" "INDDUMY")		80	102	t	)
  ( ("MFG72" "M1SLOT")		72	9	t	)
  ( ("MFG73" "M2SLOT")		73	9	t	)
  ( ("MFG74" "M3SLOT")		74	9	t	)
  ( ("MFG75" "M4SLOT")		75	9	t	)
  ( ("MFG76" "M5SLOT")		76	9	t	)
  ( ("MFG77" "M6SLOT")		77	9	t	)
  ( ("MFG78" "M7SLOT")		78	9	t	)
  ( ("MFG79" "M8SLOT")		79	9	t	)
  ( ("MFG80" "M9SLOT")		80	9	t	)
  ( ("MFG67" "L2SLOT")		67	9	t	)
  ( ("MFG80" "INDSLOT")		80	103	t	)
  ( ("RSYMBOL" "drawing")	81	0	t	)
  ( ("PSYMBOL" "drawing")	82	0	t	)
  ( ("WSYMBOL" "drawing")	83	0	t	)
  ( ("TEXT" "drawing")		85	0	t	)
  ( ("MSL" "drawing")		86	0	t	)
  ( ("IOMARK" "drawing")	87	0	t	)
  ( ("FUSEMARK" "drawing")	88	0	t	)
  ( ("FLPMARK" "drawing")	89	0	t	)
  ( ("PADMARK" "drawing")	90	0	t	)
  ( ("IOID" "drawing")		91	0	t	)
  ( ("ROMID" "drawing")		93	0	t	)
  ( ("DPID" "drawing")		94	0	t	)
  ( ("BLSPID" "drawing")	95	0	t	)
  ( ("XDIODE" "drawing")	96	0	t	)
  ( ("IRAM" "drawing")		97	0	t	)
  ( ("BDSPID" "drawing")	98	0	t	)
  ( ("PO_TEXT" "drawing")	100	0	t	)
  ( ("M1_TEXT" "drawing")	101	0	t	)
  ( ("M2_TEXT" "drawing")	102	0	t	)
  ( ("M3_TEXT" "drawing")	103	0	t	)
  ( ("M4_TEXT" "drawing")	104	0	t	)
  ( ("M5_TEXT" "drawing")	105	0	t	)
  ( ("M6_TEXT" "drawing")	106	0	t	)
  ( ("MRSDUMMY" "MRSYMBOL") 	111	30	t	)
  ( ("MIMDUMMY" "CSYMBOL")	112	30	t	)
  ( ("MIMDUMMY" "MCAP")		112	36	t	)
  ( ("BJTDUMMY" "BJTSYMBOL")	113	30	t	)
  ( ("DioDUMMY" "DSYMBOL")	114	30	t	)
  ( ("CAD115" "DIOBLK")		115	30	t	)
  ( ("INDDUMMY" "LSYMBOL")	117	30	t	)
  ( ("INDDUMMY" "IND")		117	36	t	)
  ( ("MMDUMMY" "MMSYMBOL")	118	30	t	)
  ( ("RFDUMMY" "RFSYMBOL")	119	30	t	)
  ( ("RFDUMMY" "RFMOS_S")	119	31	t	)
  ( ("MRSDUMMY" "SIZE1")		111	33	t	)
  ( ("MIMDUMMY" "SIZE2")		112	33	t	)
  ( ("BJTDUMMY" "SIZE3") 		113	33	t	)
  ( ("DioDUMMY" "SIZE4") 		114	33	t	)
  ( ("CAD115" "SIZE5") 		115	33	t	)
  ( ("CAD116" "SIZE6") 		116	33	t	)
  ( ("INDDUMMY" "SIZE7") 		117	33	t	)
  ( ("MMDUMMY" "SIZE8") 		118	33	t	)
  ( ("RFDUMMY" "SIZE9") 		119	33	t	)
  ( ("MRSDUMMY" "SIZE10")		111	34	t	)
  ( ("MIMDUMMY" "SIZE11")		112	34	t	)
  ( ("BJTDUMMY" "SIZE12")		113	34	t	)
  ( ("ACL" "drawing")		120	0	t	)
  ( ("PHL" "drawing")		121	0	t	)
 ) ;streamLayers

) ;




